# Generated by Django 3.0 on 2019-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.AddField(
            model_name='image',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
