# Generated by Django 3.0.3 on 2020-03-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
