# Generated by Django 3.0.3 on 2020-02-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200226_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='imguploads'),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='private_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='public_key',
            field=models.TextField(),
        ),
    ]
