# Generated by Django 3.0.3 on 2020-04-30 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='UserRelation',
        ),
    ]
